project_id = "local"

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322
shadow_port = 54323
major_version = 15

[studio]
enabled = true
port = 54325

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]

[auth.email]
enable_confirmations = false
